spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jooq:
    sql-dialect: postgres_9_5
  rabbitmq:
    host: localhost
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
bernmobil:
  mappingrepository:
    datasource:
      url: jdbc:postgresql://${RDS_MAPPING_HOSTNAME}:${RDS_MAPPING_PORT}/${RDS_MAPPING_DB_NAME}
      username: ${RDS_MAPPING_USERNAME}
      password: ${RDS_MAPPING_PASSWORD}
  jobrepository:
    datasource: jdbc:sqlite:repository.sqlite
  staticsource:
    url: https://wp-test.bernmobil.ch/gtfs/827/static.zip?apikey=b4059f45-9b52-4511-y68f-0fdfd0fa11c1
    # Notice trailing slash
    folder: /tmp/gtfs/
  amqp:
    fanout-queue: ch.bernmobil.vibe.update-queue


