spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: Postgres
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
bernmobil:
  mappingrepository:
    datasource:
      url: jdbc:postgresql://${RDS_MAPPING_HOSTNAME}:${RDS_MAPPING_PORT}/${RDS_MAPPING_DB_NAME}
      username: ${RDS_MAPPING_USERNAME}
      password: ${RDS_MAPPING_PASSWORD}
  jobrepository:
    datasource: jdbc:sqlite
    name: repository.sqlite
    driver-class-name: org.sqlite.JDBC
  staticsource:
    url: https://opentransportdata.swiss/de/dataset/b408f747-9838-4c05-bb98-10dac3996f17/resource/940059a1-abf5-41d6-9f75-5474eb5fc8ff/download/gtfsfp20182018-03-21.zip
    folder: /tmp/gtfs/
  amqp:
    fanout-queue: ch.bernmobil.vibe.update-queue
  history:
    size: 2
    timeout-duration: 30
  batch:
    chunk-size: 100
    schedule: 0 0 2 1/1 * ?


